branch-defaults:
  default:
    environment: flask-production
    group_suffix: null
  main:
    environment: flask-production
  master:
    environment: flask-production
environment-defaults:
  Awsdeploy-env:
    branch: default
    repository: codecommit-origin
  Pulseai-env:
    branch: null
    repository: null
  flask-production:
    branch: null
    repository: null
global:
  application_name: pulse
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.9
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
